export const REGISTER = 'REGISTER';

export const SET_USER_DATA = 'SET_USER_DATA';

export const RETRIEVE_ALL_ACTIONS = 'RETRIEVE_ALL_ACTIONS';
export const RETRIEVE_USER_ACTIONS = 'RETRIEVE_USER_ACTIONS';

export const RETRIEVE_ALL_CAMPAIGNS = 'RETRIEVE_ALL_CAMPAIGNS';

export const RETRIEVE_USER_ASSIGNMENTS = 'RETRIEVE_USER_ASSIGNMENTS';

export const RETRIEVE_USER_MEMBERSHIPS = 'RETRIEVE_USER_MEMBERSHIPS';
